seedvault-app/seedvault

- app/src/main/java/com/stevesoltys/backup/activity/PackageListActivity.java
- app/src/main/java/com/stevesoltys/backup/activity/PopupWindowUtil.java
- app/src/main/java/com/stevesoltys/backup/activity/backup/BackupPopupWindowListener.java
- app/src/main/java/com/stevesoltys/backup/activity/backup/CreateBackupActivity.java
- app/src/main/java/com/stevesoltys/backup/activity/backup/CreateBackupActivityController.java
- app/src/main/java/com/stevesoltys/backup/activity/restore/RestoreBackupActivity.java
- app/src/main/java/com/stevesoltys/backup/activity/restore/RestoreBackupActivityController.java
- app/src/main/java/com/stevesoltys/backup/activity/restore/RestoreObserver.java
- app/src/main/java/com/stevesoltys/backup/activity/restore/RestorePopupWindowListener.java
- app/src/main/java/com/stevesoltys/backup/security/CipherUtil.java
- app/src/main/java/com/stevesoltys/backup/security/KeyGenerator.java
- app/src/main/java/com/stevesoltys/backup/service/PackageService.java
- app/src/main/java/com/stevesoltys/backup/service/TransportService.java
- app/src/main/java/com/stevesoltys/backup/service/backup/BackupObserver.java
- app/src/main/java/com/stevesoltys/backup/service/backup/BackupService.java
- app/src/main/java/com/stevesoltys/backup/service/restore/RestoreObserver.java
- app/src/main/java/com/stevesoltys/backup/service/restore/RestoreService.java
- app/src/main/java/com/stevesoltys/backup/transport/component/provider/ContentProviderBackupComponent.java
- app/src/main/java/com/stevesoltys/backup/transport/component/provider/ContentProviderBackupConfiguration.java
- app/src/main/java/com/stevesoltys/backup/transport/component/provider/ContentProviderBackupConfigurationBuilder.java
- app/src/main/java/com/stevesoltys/backup/transport/component/provider/ContentProviderBackupConstants.java
- app/src/main/java/com/stevesoltys/backup/transport/component/provider/ContentProviderBackupState.java
- app/src/main/java/com/stevesoltys/backup/transport/component/provider/ContentProviderRestoreComponent.java
- app/src/main/java/com/stevesoltys/backup/transport/component/provider/ContentProviderRestoreState.java
- app/src/main/res/values/strings.xml
1. Add prompt for entering password during backup and restore.
2. Use PBKDF2 to generate a secret key that is used to encrypt backups.
3. Store salt in backup zip file.
4. Fetch salt from backup zip file during restore and use it to decrypt restoration data.
> Add support for encrypted backups

- app/src/main/AndroidManifest.xml
- build.gradle
as new version require us to remove targetSdkVersion from Manifest
> Downgrade Android Gradle plugin

- Android.mk
I forgot some things.
And upon testing with the latest code (not the latest release), I found it doesn't compile, hence the pre-optimization disabling.
> Android.mk: Actually make it work

- app/src/debug/res/values/config.xml
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/stevesoltys/seedvault/ui/RequireProvisioningActivity.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageRootFetcher.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageViewModel.kt
- app/src/main/res/values/config.xml
- build.gradle
> Allow OEMs to configure backup storage whitelist

- app/src/main/java/com/stevesoltys/seedvault/settings/AboutDialogFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsFragment.kt
- app/src/main/res/layout/fragment_about.xml
- app/src/main/res/menu/settings_menu.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
- build.gradle
> Add About page

- app/build.gradle
- app/src/main/java/com/stevesoltys/seedvault/BackupNotificationManager.kt
- app/src/main/java/com/stevesoltys/seedvault/crypto/KeyManager.kt
- app/src/main/java/com/stevesoltys/seedvault/metadata/MetadataManager.kt
- app/src/main/java/com/stevesoltys/seedvault/restore/InstallProgressAdapter.kt
- app/src/main/java/com/stevesoltys/seedvault/restore/RestoreProgressAdapter.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/AppStatusAdapter.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/AppStatusFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsActivity.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsViewModel.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/BackupCoordinator.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/AppViewHolder.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/UiUtils.kt
- app/src/main/res/drawable/ic_apps.xml
- app/src/main/res/drawable/ic_block_yellow.xml
- app/src/main/res/drawable/ic_cloud_done.xml
- app/src/main/res/drawable/ic_radio_button_unchecked_yellow.xml
- app/src/main/res/layout/fragment_app_status.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
- app/src/test/java/com/stevesoltys/seedvault/transport/backup/BackupCoordinatorTest.kt
> Show list of apps and their backup status

- app/src/main/res/values/strings.xml
* Don't use camel case, following AOSP applications
* Set app name and Nextcloud as untranslatable
> String improvements

- README.md
let users know that A10 is needed
> add requirements topic

- app/build.gradle
- app/src/androidTest/java/com/stevesoltys/seedvault/DocumentsStorageTest.kt
- app/src/androidTest/java/com/stevesoltys/seedvault/PluginTest.kt
- app/src/main/java/com/stevesoltys/seedvault/plugins/saf/DocumentsProviderFullRestorePlugin.kt
- app/src/main/java/com/stevesoltys/seedvault/plugins/saf/DocumentsProviderRestorePlugin.kt
- app/src/main/java/com/stevesoltys/seedvault/plugins/saf/DocumentsStorage.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsManager.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/restore/KVRestorePlugin.kt
- app/src/sharedTest/java/com/stevesoltys/seedvault/TestUtils.kt
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Add instrumentation tests for storage plugin (SAF)

- app/build.gradle
- app/src/androidTest/java/com/stevesoltys/seedvault/PluginTest.kt
- app/src/androidTest/java/com/stevesoltys/seedvault/plugins/saf/DocumentsStorageTest.kt
- app/src/main/java/com/stevesoltys/seedvault/App.kt
- app/src/main/java/com/stevesoltys/seedvault/BackupNotificationManager.kt
- app/src/main/java/com/stevesoltys/seedvault/NotificationBackupObserver.kt
- app/src/main/java/com/stevesoltys/seedvault/metadata/MetadataManager.kt
- app/src/main/java/com/stevesoltys/seedvault/plugins/saf/DocumentsProviderKVBackup.kt
- app/src/main/java/com/stevesoltys/seedvault/plugins/saf/DocumentsStorage.kt
- app/src/main/java/com/stevesoltys/seedvault/restore/RestoreErrorBroadcastReceiver.kt
- app/src/main/java/com/stevesoltys/seedvault/restore/RestoreProgressAdapter.kt
- app/src/main/java/com/stevesoltys/seedvault/restore/RestoreViewModel.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsActivity.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsViewModel.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/ConfigurableBackupTransportService.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/BackupCoordinator.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/BackupModule.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/KVBackup.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/PackageService.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/restore/RestoreCoordinator.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/AppViewHolder.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/notification/BackupNotificationManager.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/notification/NotificationBackupObserver.kt
- app/src/main/res/values/strings.xml
- app/src/sharedTest/java/com/stevesoltys/seedvault/TestUtils.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/CoordinatorIntegrationTest.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/TransportTest.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/backup/BackupCoordinatorTest.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/backup/KVBackupTest.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/restore/RestoreCoordinatorTest.kt
This PR shows more fine-grained progress (instead of stalling for minutes in the beginning), a numeric percentage and actual totals at the end. There's also some smaller fixes for Nextcloud related instrumentation tests.
> Improve backup progress system notifications

- README.md
- app/src/main/java/com/stevesoltys/seedvault/App.kt
- app/src/main/java/com/stevesoltys/seedvault/metadata/MetadataManager.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsManager.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsViewModel.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/ConfigurableBackupTransport.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/restore/ApkInstaller.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageViewModel.kt
- app/src/main/res/layout/fragment_storage_root.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/stevesoltys/seedvault/metadata/MetadataManagerTest.kt
This MR contains some smaller fixes that did not fit in anywhere else.
It also enables StrictMode on `userdebug` builds, so we can spot issues like blocking work on Ui Thread or failing to close streams early on.
> Assorted fixes

- app/lint.xml
- app/src/main/java/com/stevesoltys/seedvault/transport/ConfigurableBackupTransport.kt
- app/src/main/res/layout/fragment_storage_root.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-el/strings.xml
- app/src/main/res/values-es-rUS/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-he/strings.xml
- app/src/main/res/values-hr/strings.xml
- app/src/main/res/values-is/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt-rBR/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-tzm/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
Backport select translation related fixes from master to android10 and import previous weblate translations.
> android10: backport translation fixes

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/stevesoltys/seedvault/plugins/saf/DocumentsStorage.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/BackupManagerSettings.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsActivity.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsManager.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsViewModel.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/BackupCoordinator.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/KVBackup.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/restore/RestoreCoordinator.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/RequireProvisioningActivity.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/RequireProvisioningViewModel.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/notification/BackupNotificationManager.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageActivity.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageRootFetcher.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageRootResolver.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageRootsFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/storage/StorageViewModel.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/backup/BackupCoordinatorTest.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/backup/KVBackupTest.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/restore/RestoreCoordinatorTest.kt
- logcat-verbose.sh
- whitelist_com.stevesoltys.seedvault.xml
This MR contains various smaller fixes and improvements.
Please see the individual commit messages for details.
> Various Fixes

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/stevesoltys/seedvault/settings/AboutDialogFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/PackageService.kt
- app/src/main/res/layout/fragment_about.xml
- app/src/main/res/values/strings.xml
> Move to different versioning scheme and show version in About dialog

- app/src/androidTest/java/com/stevesoltys/seedvault/transport/backup/PackageServiceTest.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/AppListRetriever.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/AppStatusAdapter.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/BackupCoordinator.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/PackageService.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/AppBackupState.kt
- app/src/main/res/layout/list_item_app_section_title.xml
- app/src/main/res/layout/list_item_app_status.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
- app/src/test/java/com/stevesoltys/seedvault/transport/backup/BackupCoordinatorTest.kt
> Group app status list into three sections

- app/src/main/res/values/strings.xml
Change-Id: I0365a381f4c2f28d3d61b4f90c66af9e557a50d2
> strings: Avoid using camel case

- app/src/main/java/com/stevesoltys/seedvault/transport/backup/KVBackup.kt
This might help with tracking down https://github.com/seedvault-app/seedvault/issues/152#issuecomment-747845729
> Add message to AssertionError to track down why it happens

- app/src/main/java/com/stevesoltys/seedvault/App.kt
- app/src/main/java/com/stevesoltys/seedvault/crypto/CipherFactory.kt
- app/src/main/java/com/stevesoltys/seedvault/crypto/Crypto.kt
- app/src/main/java/com/stevesoltys/seedvault/crypto/KeyManager.kt
- app/src/main/java/com/stevesoltys/seedvault/plugins/saf/DocumentsProviderBackupPlugin.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsActivity.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/BackupPlugin.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/recoverycode/RecoveryCodeInputFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/recoverycode/RecoveryCodeViewModel.kt
- app/src/main/res/drawable/ic_vpn_key.xml
- app/src/main/res/layout/fragment_recovery_code_input.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
https://user-images.githubusercontent.com/244947/105069500-ca295a00-5a60-11eb-9fe0-e5666a63a65c.mp4
Closes #62
> Allow user to verify and generate new recovery code

- app/src/main/res/values/strings.xml
* This should finally cover all strings
> Fix a couple camel case issues in strings

- app/src/main/res/values/strings.xml
Change-Id: Id0f0587b5174810de9e7d8036ca7e1264ea43c76
> On phones we tap, not click!

- app/src/main/res/layout/fragment_recovery_code_output.xml
- app/src/main/res/layout/list_item_recovery_code_output.xml
Replaces https://github.com/seedvault-app/seedvault/pull/236
> Make recovery code fit on smaller screens

- app/src/main/AndroidManifest.xml
- contactsbackup/src/main/AndroidManifest.xml
Change-Id: I3817cf2320379504a8205125e7fa4894e3e57deb
> Bump version to 11-1.2

- app/src/main/AndroidManifest.xml
- contactsbackup/src/main/AndroidManifest.xml
Change-Id: Ifd639c3c9205b417d1ec37c8e7a11a2119b5cb48
> SeedVault 2.0: Now with storage backup!

- app/src/main/AndroidManifest.xml
- contactsbackup/src/main/AndroidManifest.xml
* Only change here is the BIP39 dependency replacement, however
I'm still bumping version so that it's easy to figure out in case
there ever was a build with just 2.0 and not this due to whatever reason
Change-Id: I9783d5e038d002e871c09be6fe61174c5a5b901f
> Bump version to 11-2.1

- app/src/main/res/layout/recovery_code_input.xml
to prevent potential cloud learning or otherwise leaking code
> Disable spell-checker on recovery code input

- README.md
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/stevesoltys/seedvault/ui/recoverycode/RecoveryCodeActivity.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/recoverycode/RecoveryCodeInputFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/ui/recoverycode/RecoveryCodeViewModel.kt
- app/src/main/res/values/strings.xml
This will help to prevent data extraction via Seedvault when somebody gets hold of an unlocked phone. However, it will not help against someone able to force you to provide fingerprints or other device secrets.
Fixes #245
> Ask for system authentication before storing a new recovery code

- app/src/main/java/com/stevesoltys/seedvault/settings/ExpertSettingsFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsFragment.kt
- app/src/main/java/com/stevesoltys/seedvault/settings/SettingsManager.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/BackupModule.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/FullBackup.kt
- app/src/main/java/com/stevesoltys/seedvault/transport/backup/KVBackup.kt
- app/src/main/res/menu/settings_menu.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings_expert.xml
- app/src/test/java/com/stevesoltys/seedvault/transport/CoordinatorIntegrationTest.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/backup/FullBackupTest.kt
- app/src/test/java/com/stevesoltys/seedvault/transport/backup/KVBackupTest.kt
I tested this by pushing extra files to an app's private dir. It didn't get backed up due to exceeding quota with default settings, but did get backed up enabling the new expert setting.
> Add expert settings with an option for unlimited quota

- CHANGELOG.md
- app/src/main/AndroidManifest.xml
- contactsbackup/src/main/AndroidManifest.xml
Also updates changelog
Closes: #292
> Bump version to 11-2.2

- README.md
Per https://github.com/seedvault-app/seedvault/issues/301
> README: master is now deprecated
